# Generated by Django 5.0.4 on 2024-10-23 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('platform', models.IntegerField(choices=[(0, 'Steam'), (1, 'Switch')], null=True)),
                ('steam_app_id', models.IntegerField(null=True, unique=True)),
                ('genres', models.ManyToManyField(to='game_backlog.genre')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steam_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('steam_id', models.CharField(max_length=100, null=True, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='SuggestionGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.IntegerField(choices=[(0, 'By Genre')])),
                ('game_list', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_backlog.user')),
            ],
            options={
                'verbose_name': 'suggestion game',
                'verbose_name_plural': 'suggestion games',
            },
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed')], null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('playtime', models.IntegerField(default=0)),
                ('favourite', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_backlog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_backlog.user')),
            ],
            options={
                'verbose_name': 'backlog',
                'verbose_name_plural': 'backlogs',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_backlog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_backlog.user')),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlists',
            },
        ),
        migrations.AddConstraint(
            model_name='backlog',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_backlog_user_game'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_wishlist_user_game'),
        ),
    ]
