# Generated by Django 5.1.2 on 2024-10-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
