# Generated by Django 5.0.4 on 2024-05-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0003_game_app_id_alter_user_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='app_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
