# Generated by Django 5.0.4 on 2024-05-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0005_alter_game_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='app_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
