# Generated by Django 5.0.4 on 2024-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0007_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='app_id',
        ),
        migrations.AddField(
            model_name='backlog',
            name='playtime',
            field=models.IntegerField(default=0),
        ),
    ]
