# Generated by Django 5.0.4 on 2024-06-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0009_genre_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='backlog',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game'),
        ),
    ]
