# Generated by Django 5.0.4 on 2024-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0010_alter_genre_code_backlog_unique_user_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game_backlog.genre'),
        ),
    ]
