# Generated by Django 5.0.4 on 2024-06-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0013_alter_backlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_backlog.user'),
        ),
    ]
