# Generated by Django 5.0.4 on 2024-07-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0015_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Steam'), (1, 'Switch')], null=True),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='steam_app_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
