# Generated by Django 5.0.4 on 2024-07-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_backlog', '0016_remove_game_platform_game_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='status',
            new_name='platform',
        ),
    ]
