# Generated by Django 5.0.4 on 2024-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_backlog", "0017_rename_status_game_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="backlog",
            name="favourite",
            field=models.BooleanField(default=False),
        ),
    ]
