# Generated by Django 5.0.4 on 2024-08-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_backlog", "0019_rename_username_user_steam_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backlog",
            options={"verbose_name": "backlog", "verbose_name_plural": "backlogs"},
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "game", "verbose_name_plural": "games"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "genre", "verbose_name_plural": "genres"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
