# Generated by Django 5.0.4 on 2024-08-27 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_backlog", "0020_alter_backlog_options_alter_game_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={"verbose_name": "wishlist", "verbose_name_plural": "wishlists",},
        ),
        migrations.RemoveConstraint(model_name="backlog", name="unique_user_game",),
        migrations.AddConstraint(
            model_name="backlog",
            constraint=models.UniqueConstraint(
                fields=("user", "game"), name="unique_backlog_user_game"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game_backlog.game"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game_backlog.user"
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("user", "game"), name="unique_wishlist_user_game"
            ),
        ),
    ]
