# Generated by Django 5.0.4 on 2024-09-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_backlog", "0021_wishlist_remove_backlog_unique_user_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="steam_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
