# Generated by Django 5.0.4 on 2024-09-04 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_backlog", "0022_alter_user_steam_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionGame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("suggestion_type", models.IntegerField(choices=[(0, "By Genre")])),
                ("game_list", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_backlog.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "suggestion game",
                "verbose_name_plural": "suggestion games",
            },
        ),
    ]
